//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindRuby.Cowin.Entities1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentreDetail
    {
        public int CentreID { get; set; }
        public string CentreName { get; set; }
        public int Pincode { get; set; }
        public string VaccineName { get; set; }
        public int cost { get; set; }
        public int AvailableVaccine { get; set; }
    }
}
