//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindRuby.Cowin.Entities1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Aadhar { get; set; }
        public bool Dose1Status { get; set; }
        public bool Dose2Status { get; set; }
        public bool Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
    }
}
